name: aquatic
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/scalabs

environment:
  sdk: '>=2.17.2 <3.0.0'


dependencies: 
  archive: ^3.3.1
  dart_amqp: ^0.2.1
  gcloud: ^0.8.5
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  intl: ^0.17.0
  markdown: ^4.0.0
  path: ^1.8.0
  week_of_year: ^2.0.0
  xml: ^6.1.0
  yaml: ^3.1.0

#   path: ^1.8.0

dev_dependencies:
  dartclub_lint: ^0.3.1+2
  test: ^1.16.0
